services:
  postgres:
    image: postgres:15
    container_name: todoapp_postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todoapp_network

  adminer:
    image: adminer
    container_name: todoapp_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - todoapp_network

volumes:
  postgres_data:

networks:
  todoapp_network:
    driver: bridge